# Generated by Django 3.0.6 on 2020-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200905_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
